export const INIT_WORKOUT = "INIT_WORKOUT";
export const FETCH_WORKOUT_SUCCESS = "FETCH_WORKOUT_SUCCESS";
export const FETCH_WORKOUT_FAIL = "FETCH_WORKOUT_FAIL";
export const SELECTED_WORKOUT = "SELECTED_WORKOUT";
export const DE_SELECTED_WORKOUT = "DE_SELECTED_WORKOUT";
export const CLEAR_SELECTED_WORKOUTS = "CLEAR_SELECTED_WORKOUTS";

export const INIT_NUTRITION = "INIT_NUTRITION";
export const FETCH_NUTRITION_SUCCESS = "FETCH_NUTRITION_SUCCESS";
export const FETCH_NUTRITION_FAIL = "FETCH_NUTRITION_FAIL";
export const SELECTED_NUTRITION = "SELECTED_NUTRITION";
export const DE_SELECTED_NUTRITION = "DE_SELECTED_NUTRITION";
export const CLEAR_SELECTED_NUTRITION = "CLEAR_SELECTED_NUTRITION";
